Use a `SortedSet` to sort the results of `Get-SecretInfo`
PowerShell/SecretManagement pull request #219
Opened 2024-02-16 23:22 UTC by andyleejordan

Instead of a `SortedDictionary` so that keys don't have to be unique. Fixes #95.

2024-02-20 15:33 UTC, JustinGrote commented
@andyleejordan are there any potential regressions with, say, piping two secretinfo results with the same name to `get-secret`?

2024-02-20 20:53 UTC, andyleejordan commented
I am unsure and need to get some more folks to look at this. Also, I had a thought that it probably doesn't even need to build a set, I don't see why we can't just sort the array with the comparer I added.

2024-02-20 21:02 UTC, andyleejordan commented
Yup, that's better. No idea why this had a dictionary in the first place, all it needed was a comparer.

2024-02-20 21:11 UTC, andyleejordan commented
> @andyleejordan are there any potential regressions with, say, piping two secretinfo results with the same name to `get-secret`?

Well, instead of erroring because of the duplicate names it should now correctly print them both.

2024-02-21 00:29 UTC, SteveL-MSFT requested changes
You should add a test.

2024-02-21 00:32 UTC, SteveL-MSFT commented
It's too bad we didn't catch this sooner and make the secret name case-insensitive, but it would be a breaking change now.

2024-02-21 00:32 UTC, andyleejordan commented
Fair 😆 I'll figure that out...I need to make another PR setting up build/test tasks because that's been the slowest part of this.

2024-02-21 01:11 UTC, andyleejordan commented
> It's too bad we didn't catch this sooner and make the secret name case-insensitive, but it would be a breaking change now.

My understanding of it is that secret names _aren't_ necessarily case-sensitive, at least as far as `SecretManagement` is concerned. It's up to the vault implementations to decide their case sensitivity...which is what revealed this bug. I think `SecretStore` is case-sensitive, but that shouldn't really matter here.

2025-12-31 15:45 UTC, GYPSIERose923 approved these changes

2026-06-17 21:46 UTC, andyleejordan commented
Closing per #247

2026-06-17 21:46 UTC, closed without merging